
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc

sudo: required

addons:
  apt:
    packages:
      - autotools-dev
      - libcap-dev
      - libssl-dev
      - g++
      - libfuse-dev
      - pkg-config
      - libattr1-dev
      - patch
      - python-dev
      - unzip
      - uuid-dev
      - libc6-dev
      - valgrind
      - voms-dev
      - gdb
  homebrew:
    casks:
      - osxfuse
    update: true

script:
  - ci/run_travis.sh

notifications:
  email: false
